name: Miri Unit Tests

on:
  workflow_call:
  push:
    paths:
      - ".github/workflows/test_miri.yml"

jobs:
  test:
    name: Miri Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 1
      - name: Install Rust toolchain with Miri
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          components: miri
          toolchain: nightly
      - name: Cache cargo registry, index, and targets
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 #v2
        with:
          prefix-key: "cargo-miri"
      - name: Run Miri tests
        run: |
          RUST_BACKTRACE=1 \
          MIRIFLAGS="-Zmiri-backtrace=full" \
          cargo +nightly miri test --all --locked --all-features --verbose
        shell: bash
