name: Miri Unit Tests

on:
  workflow_call:

jobs:
  test:
    name: Miri Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1
      - name: Install Rust toolchain with Miri
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          components: miri
          toolchain: nightly
      - name: Run Miri tests
        run: |
          RUST_BACKTRACE=1 \
          MIRIFLAGS="-Zmiri-backtrace=full" \
          cargo +nightly miri test --package chase_seq --locked --all-features
